export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

export const productConstants = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
  GET_PRODUCT_PAGE_REQUEST: "GET_PRODUCT_PAGE_REQUEST",
  GET_PRODUCT_PAGE_SUCCESS: "GET_PRODUCT_PAGE_SUCCESS",
  GET_PRODUCT_PAGE_FAILURE: "GET_PRODUCT_PAGE_FAILURE",
  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
  RATE_PRODUCT_REQUEST: "RATE_PRODUCT_REQUEST",
  RATE_PRODUCT_SUCCESS: "RATE_PRODUCT_SUCCESS",
  RATE_PRODUCT_FAILURE: "RATE_PRODUCT_FAILURE",
  GET_PRODUCT_RATINGS_REQUEST: "GET_PRODUCT_RATINGS_REQUEST",
  GET_PRODUCT_RATINGS_SUCCESS: "GET_PRODUCT_RATINGS_SUCCESS",
  GET_PRODUCT_RATINGS_FAILURE: "GET_PRODUCT_RATINGS_FAILURE",
  GET_TRENDING_PRODUCTS_REQUEST: "GET_TRENDING_PRODUCTS_REQUEST",
  GET_TRENDING_PRODUCTS_SUCCESS: "GET_TRENDING_PRODUCTS_SUCCESS",
  GET_TRENDING_PRODUCTS_FAILURE: "GET_TRENDING_PRODUCTS_FAILURE",
};

export const authConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",
  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const userConstants = {
  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",

  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",

  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};

export const favoriteConstants = {
  ADD_TO_FAVORITE_REQUEST: "ADD_TO_FAVORITE_REQUEST",
  ADD_TO_FAVORITE_SUCCESS: "ADD_TO_FAVORITE_SUCCESS",
  ADD_TO_FAVORITE_FAILURE: "ADD_TO_FAVORITE_FAILURE",

  GET_USER_FAVORITES_REQUEST: "GET_USER_FAVORITES_REQUEST",
  GET_USER_FAVORITES_SUCCESS: "GET_USER_FAVORITES_SUCCESS",
  GET_USER_FAVORITES_FAILURE: "GET_USER_FAVORITES_FAILURE",

  REMOVE_FROM_FAVORITES_REQUEST: "REMOVE_FROM_FAVORITES_REQUEST",
  REMOVE_FROM_FAVORITES_SUCCESS: "REMOVE_FROM_FAVORITES_SUCCESS",
  REMOVE_FROM_FAVORITES_FAILURE: "REMOVE_FROM_FAVORITES_FAILURE",
};

export const slideConstants = {
  GET_SLIDES_REQUEST: "GET_SLIDES_REQUEST",
  GET_SLIDES_SUCCESS: "GET_SLIDES_SUCCESS",
  GET_SLIDES_FAILURE: "GET_SLIDES_FAILURE",
};

export const searchConstants = {
  SEARCH_PRODUCT_REQUEST: "SEARCH_PRODUCT_REQUEST",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",
};
