import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '@/components/Footer/Footer'
import SuperDeal from '@/components/SuperDeal/SuperDeal'
import TrendingProduct from '@/components/TrendingProduct/TrendingProduct'
import RecentlyView from '@/components/RecentlyView/RecentlyView'

  
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ekpoloke Ecommerce Shopping In  Bangladesh </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#F2F2F2]'>
        <SuperDeal></SuperDeal>
        <TrendingProduct></TrendingProduct>
        <RecentlyView></RecentlyView>
        <Footer />  
      </main>
    </>
  )
}
