import Head from "next/head";
import { Inter, Pacifico, Roboto } from "@next/font/google";
import Footer from "@/components/Footer/Footer";
import Carousel from "@/components/Carousel/Carousel";
import SuperDeal from "@/components/SuperDeal/SuperDeal";
import TrendingProduct from "@/components/TrendingProduct/TrendingProduct";
import RecentlyView from "@/components/RecentlyView/RecentlyView";
import HomePage from "@/components/HomePage/HomePage";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ekpoloke Ecommerce Shopping In Bangladesh </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={`bg-[#F2F2F2] ${roboto.className}`}>
        <Carousel />
        <HomePage></HomePage>
      </main>
    </>
  );
}
