import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '@/components/Footer/Footer'
import Carousel from '@/components/Carousel/Carousel'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ekpoloke Ecommerce Shopping In  Bangladesh </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Carousel/>
        <Footer />
      </main>
    </>
  )
}
